spring:
  profiles:
    include: git
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/armory-sandu-org/eap-config.git
          basedir: /tmp/config-repo
          refresh-rate: 10
